from art import *
from os import system as sys
import time


tprint("WELCOME TO Mysterious Cave")
print("Press 1 to PLAY : ")
print("Press 0 to QUIT : ")

choice = int(input())
if choice == 1:
	sys('cls')
	print("You are in front of a BIG ")
	tprint("CAVE")
	print("1. GO INSIDE THE CAVE !!!")
	print("2. Get a FLASH LIGHT and then GO INSIDE THE CAVE !!! ")
	choice = int(input())
	if choice == 1:
		sys('cls')
		tprint("DARK", font = "random")
		print("IT'S REALLY DARK INSIDE !!! ")
		print("You see a small LIGHT coming from an opening .... ")
		time.sleep(5)
		print("What will you do ? .... ")
		print("1. Get OUT and leave the MYSTERIOUS CAVE because you are AFRAID of dark ...!")
		print("2. Follow the light coming from the opening ... ! ")
		choice = int(input())
		if choice == 1:
			sys('cls')
			print("Your Adventure ENDED, but what if you followed that light ... !")
			time.sleep(3)
			tprint("GAME OVER")
		elif choice == 2:
			sys('cls')
			print("You are following the LIGHT .")
			time.sleep(1)
			sys('cls')
			print("You are following the LIGHT ..")
			time.sleep(1)
			sys('cls')
			print("You are following the LIGHT ...")
			time.sleep(1)
			sys('cls')
			print("You are following the LIGHT ....")
			time.sleep(1)
			sys('cls')
			print("You are following the LIGHT .....")
			time.sleep(1)
			sys('cls')
			
			tprint("!!!")
			print("While following the light you got bumped . !!!\n\n\n\a")
			print("You bumped with BOX !!! \n\n\n")
			
			print("What will you DO ? ... !")
			print("1. LEAVE THE BOX AND FOLLOW THE LIGHT....")
			print("2. OPEN THE BOX AND TRY TO SENSE WHAT'S INSIDE IT ....")
			choice = int(input())
			if choice == 1:
				sys('cls')
				print("You CAME OUT from the other END of the cave....")
				time.sleep(3)
				sys('cls')
				print("But THAT ")
				tprint("BOX")
				print("remained a MYSTERY ")
				time.sleep(5)
				sys('cls')
				tprint("GAME OVER")
			elif choice == 2:
				sys('cls')
				print("YOU ARE ")
				tprint("BIT ... ! ")
				print("by something ..... ")
				time.sleep(5)
				print("YOU  FELL ")
				tprint("UNCONSCIOUS ... !")
				time.sleep(5)
				sys('cls')
				tprint("GAME OVER")
	elif choice == 2:
		sys('cls')
		print("You took a Flash Light and WENT INSIDE THE CAVE...")
		time.sleep(2)
		print("You are Exploring the cave .")
		time.sleep(1)
		sys('cls')
		print("You are Exploring the cave ...")
		time.sleep(1)
		sys('cls')
		print("You are Exploring the cave .....")
		time.sleep(1)
		sys('cls')
		print("You are Exploring the cave .......")
		time.sleep(1)
		sys('cls')
		print("You Saw a ")
		tprint("BOX ")
		time.sleep(1)
		print("What will YOU DO ?...")
		print("1. OPEN THE BOX AND SEE WHAT'S INSIDE...")
		print("2. LEAVE THE BOX...")
		choice = int(input())
		if choice == 1:
			sys('cls')
			tprint("SNAKE ... ", font="random")
			print("A Snake Comes Out...")
			time.sleep(4)
			print("Scared of you it RAN AWAY...")
			time.sleep(4)
			sys('cls')
			print("The BOX is in front of you ....")
			print("What Will You DO ? ")
			print("1. LOOK INSIDE THE BOX ... ")
			print("2. DON'T LOOK INSIDE THE BOX AND MOVE ON ... ")
			choice = int(input())
			if choice == 1:
				sys('cls')
				print("You Find A ")
				tprint("MYSTERIOUS CUBE.")
				time.sleep(4)
				print("What will you DO ? ")
				print("1. TAKE THE CUBE WITH YOU ..")
				print("2. LEAVE THE CUBE AND CONTINUE ..")
				choice = int(input())
				if choice == 1:
					sys('cls')
					print("After a While you came out of the CAVE...")
					time.sleep(4)
					print("Wondering what is the use of that Mysterious CUBE .. ")
					time.sleep(4)
					sys('cls')
					tprint("WAIT FOR")
					tprint("THE NEXT")
					tprint("PART OF")
					tprint("THE GAME")
					tprint("MYSTERIOUS CUBE")
					time.sleep(5)
					sys('cls')
					tprint("THANKS FOR")
					tprint("PLAYING ;)")
				elif choice == 2:
					sys('cls')
					print("After a While you came out of the CAVE...")
					time.sleep(4)
					print("Wondering what was that Mysterious CUBE .. ")
					time.sleep(4)
					sys('cls')
					print("But What if you brought that CUBE with YOU...")
					time.sleep(4)
					sys('cls')
					tprint("GAME OVER")
			elif choice == 2:
				sys('cls')
				print("You CAME OUT from the other END of the cave....")
				time.sleep(3)
				sys('cls')
				print("But THAT ")
				tprint("BOX")
				print("remained a MYSTERY ")
				time.sleep(5)
				sys('cls')
				tprint("GAME OVER")
		elif choice == 2:
			sys('cls')
			print("You CAME OUT from the other END of the cave....")
			time.sleep(3)
			sys('cls')
			print("But THAT ")
			tprint("BOX")
			print("remained a MYSTERY ")
			time.sleep(5)
			sys('cls')
			tprint("GAME OVER")
elif choice == 0:
	exit()